version: '3'
services:
  hello:
    build: ./app
    expose:
      - "8080"
  health_sidecar:
    build: ./health_sidecar
    links: 
      - hello
    depends_on: 
      - hello
  nginx:
    image: nginx:1.16-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8090:80
    links:
      - hello
    depends_on:
      - hello
networks:
  backend:
    driver: "bridge"